export const APP_CONFIG = {
  API_TIMEOUT: 30000,
  MAX_FILE_SIZE: 5 * 1024 * 1024, // 5MB
  PAGINATION_LIMIT: 20,
  OTP_LENGTH: 6,
  OTP_COUNTDOWN: 60, // seconds
  INCOMING_REQUEST_TIMEOUT: 30, // seconds
  RIDE_PIN_LENGTH: 4,
  SOS_HOLD_DURATION: 3000, // milliseconds
  MAX_TRUSTED_CONTACTS: 5,
  LOCATION_UPDATE_INTERVAL: 5000, // milliseconds
  LOCATION_DISTANCE_INTERVAL: 10, // meters
  MAX_CHAT_IMAGE_SIZE: 2 * 1024 * 1024, // 2MB
  CURRENCY: '₱',
  CURRENCY_CODE: 'PHP',
} as const;
