-- Migration 005: Create bookings table
CREATE TABLE bookings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_number VARCHAR(20) NOT NULL UNIQUE,
    customer_id UUID NOT NULL REFERENCES users(id),
    runner_id UUID REFERENCES users(id),
    errand_type_id UUID NOT NULL REFERENCES errand_types(id),
    status VARCHAR(25) NOT NULL DEFAULT 'pending',
    pickup_address TEXT NOT NULL,
    pickup_lat DECIMAL(10, 7) NOT NULL,
    pickup_lng DECIMAL(10, 7) NOT NULL,
    pickup_contact_name VARCHAR(100),
    pickup_contact_phone VARCHAR(20),
    dropoff_address TEXT NOT NULL,
    dropoff_lat DECIMAL(10, 7) NOT NULL,
    dropoff_lng DECIMAL(10, 7) NOT NULL,
    dropoff_contact_name VARCHAR(100),
    dropoff_contact_phone VARCHAR(20),
    description TEXT,
    special_instructions TEXT,
    item_photos JSONB NOT NULL DEFAULT '[]',
    estimated_item_value DECIMAL(10, 2),
    schedule_type VARCHAR(10) NOT NULL DEFAULT 'now',
    scheduled_at TIMESTAMPTZ,
    pricing_mode VARCHAR(10) NOT NULL DEFAULT 'fixed',
    vehicle_type_rate VARCHAR(15),
    distance_km DECIMAL(8, 2),
    base_fee DECIMAL(8, 2) NOT NULL,
    distance_fee DECIMAL(8, 2) NOT NULL,
    service_fee DECIMAL(8, 2) NOT NULL,
    surcharge DECIMAL(8, 2) NOT NULL DEFAULT 0.00,
    promo_discount DECIMAL(8, 2) NOT NULL DEFAULT 0.00,
    total_amount DECIMAL(10, 2) NOT NULL,
    customer_offer DECIMAL(10, 2),
    recommended_min DECIMAL(10, 2),
    recommended_max DECIMAL(10, 2),
    runner_payout DECIMAL(10, 2),
    negotiate_expires_at TIMESTAMPTZ,
    pickup_photo_url TEXT,
    delivery_photo_url TEXT,
    signature_url TEXT,
    matched_at TIMESTAMPTZ,
    accepted_at TIMESTAMPTZ,
    picked_up_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    cancellation_reason TEXT,
    cancelled_by UUID,
    promo_code_id UUID,
    ride_pin VARCHAR(4),
    ride_pin_verified BOOLEAN NOT NULL DEFAULT FALSE,
    is_transportation BOOLEAN NOT NULL DEFAULT FALSE,
    sos_triggered BOOLEAN NOT NULL DEFAULT FALSE,
    trip_share_token VARCHAR(64) UNIQUE,
    trip_share_active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_bookings_customer_id ON bookings (customer_id);
CREATE INDEX idx_bookings_runner_id ON bookings (runner_id);
CREATE INDEX idx_bookings_status ON bookings (status);
CREATE INDEX idx_bookings_booking_number ON bookings (booking_number);
CREATE INDEX idx_bookings_created_at ON bookings (created_at);
